export enum TYPE {
  ACCESS = "ACCESS",
  REFRESH = "REFRESH",
  CONFIRMATION = "CONFIRMATION",
}

export enum REASON_FOR_REVOKE {
  SIGN_OUT = "SIGN_OUT",
  EXPIRED = "EXPIRED",
  REFRESHED = "REFRESHED",
  CONFIRMED = "CONFIRMED",
  UNKNOWN = "UNKNOWN",
}